"""Executable reference implementations for the current ARG roadmap gate."""

from .model import (
    Parameters,
    State,
    collective_mode,
    derivatives,
    intrinsic_distance_matrix,
    intrinsic_edge_lengths,
)
from .models import (
    CONTRACT_VERSION,
    MINIMUM_C0,
    PROJECTOR_TOLERANCE,
    ModelId,
    ProjectedStepResult,
    ProjectionDiagnostics,
    ProjectionTarget,
    RetractionResult,
    constraint_residual,
    derivatives_for_model,
    feedback_vector,
    local_adaptive_derivatives,
    project_node_derivative,
    projected_derivative,
    projected_rk4_step,
    retract_to_constraint,
    rk4_step,
    tangent_projector,
)

__all__ = [
    "CONTRACT_VERSION",
    "MINIMUM_C0",
    "PROJECTOR_TOLERANCE",
    "ModelId",
    "Parameters",
    "ProjectedStepResult",
    "ProjectionDiagnostics",
    "ProjectionTarget",
    "RetractionResult",
    "State",
    "collective_mode",
    "constraint_residual",
    "derivatives",
    "derivatives_for_model",
    "feedback_vector",
    "intrinsic_distance_matrix",
    "intrinsic_edge_lengths",
    "local_adaptive_derivatives",
    "project_node_derivative",
    "projected_derivative",
    "projected_rk4_step",
    "retract_to_constraint",
    "rk4_step",
    "tangent_projector",
]
