"""Minimal nonlinear dynamic relational geometry.

The implementation uses a complete undirected graph on three nodes.  The
collective mode is derived from the node states and feeds back into local,
edge, and metric dynamics.  No claim is made that these equations are physical
law; they are the first executable model of the proposed architecture.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Final

import numpy as np
from numpy.typing import NDArray

FloatArray = NDArray[np.float64]

# Fixed edge order for the three-node complete graph.
EDGES: Final[tuple[tuple[int, int], ...]] = ((0, 1), (0, 2), (1, 2))


@dataclass(frozen=True)
class Parameters:
    """Model parameters with conservative defaults."""

    alpha: float = 1.0
    beta: float = 1.0
    chi: float = 0.35
    tau_s: float = 1.0
    eta_0: float = 0.25
    eta_1: float = 1.0
    eta_2: float = 0.2
    tau_q: float = 1.0
    gamma: float = 0.8
    kappa: float = 0.4
    rho: float = 0.15
    epsilon: float = 1.0e-6

    def validate(self) -> None:
        positive = {
            "beta": self.beta,
            "tau_s": self.tau_s,
            "eta_1": self.eta_1,
            "tau_q": self.tau_q,
            "gamma": self.gamma,
            "epsilon": self.epsilon,
        }
        invalid = [name for name, value in positive.items() if value <= 0.0]
        if invalid:
            raise ValueError(f"Parameters must be positive: {', '.join(invalid)}")


@dataclass(frozen=True)
class State:
    """Three node states, three edge logits, and three metric variables."""

    x: FloatArray
    s: FloatArray
    q: FloatArray

    def __post_init__(self) -> None:
        for name, value in (("x", self.x), ("s", self.s), ("q", self.q)):
            array = np.asarray(value, dtype=np.float64)
            if array.shape != (3,):
                raise ValueError(f"{name} must have shape (3,), received {array.shape}")
            if not np.all(np.isfinite(array)):
                raise ValueError(f"{name} contains non-finite values")
            object.__setattr__(self, name, array)

    def pack(self) -> FloatArray:
        return np.concatenate((self.x, self.s, self.q))

    @classmethod
    def unpack(cls, vector: FloatArray) -> "State":
        vector = np.asarray(vector, dtype=np.float64)
        if vector.shape != (9,):
            raise ValueError(f"state vector must have shape (9,), received {vector.shape}")
        return cls(x=vector[0:3], s=vector[3:6], q=vector[6:9])


def sigmoid(value: FloatArray) -> FloatArray:
    """Numerically stable logistic activation."""

    value = np.asarray(value, dtype=np.float64)
    out = np.empty_like(value)
    nonnegative = value >= 0.0
    out[nonnegative] = 1.0 / (1.0 + np.exp(-value[nonnegative]))
    exp_value = np.exp(value[~nonnegative])
    out[~nonnegative] = exp_value / (1.0 + exp_value)
    return out


def collective_mode(x: FloatArray) -> float:
    """Endogenous whole-state observable generated by local states."""

    x = np.asarray(x, dtype=np.float64)
    return float(np.mean(x * x))


def conductances(state: State) -> FloatArray:
    """Return positive edge conductances in fixed edge order."""

    return sigmoid(state.s) * np.exp(-state.q)


def intrinsic_edge_lengths(state: State, params: Parameters) -> FloatArray:
    """Return positive state-dependent intrinsic edge lengths."""

    params.validate()
    activation = sigmoid(state.s)
    lengths = np.empty(3, dtype=np.float64)
    for edge_index, (i, j) in enumerate(EDGES):
        mismatch = state.x[i] - state.x[j]
        local_scale = np.sqrt(params.epsilon**2 + mismatch**2)
        lengths[edge_index] = np.exp(state.q[edge_index]) * local_scale / activation[edge_index]
    return lengths


def intrinsic_distance_matrix(state: State, params: Parameters) -> FloatArray:
    """Compute all-pairs shortest-path distances for the three-node graph."""

    lengths = intrinsic_edge_lengths(state, params)
    distance = np.full((3, 3), np.inf, dtype=np.float64)
    np.fill_diagonal(distance, 0.0)
    for edge_index, (i, j) in enumerate(EDGES):
        distance[i, j] = lengths[edge_index]
        distance[j, i] = lengths[edge_index]

    # Floyd-Warshall is explicit and deterministic for this tiny reference model.
    for k in range(3):
        for i in range(3):
            for j in range(3):
                candidate = distance[i, k] + distance[k, j]
                if candidate < distance[i, j]:
                    distance[i, j] = candidate
    return distance


def derivatives(state: State, params: Parameters) -> State:
    """Evaluate the coupled nonlinear right-hand side."""

    params.validate()
    x, s, q = state.x, state.s, state.q
    c = collective_mode(x)
    weights = conductances(state)

    dx = params.alpha * x - params.beta * x**3 - params.chi * c * x
    ds = np.empty(3, dtype=np.float64)
    dq = np.empty(3, dtype=np.float64)

    for edge_index, (i, j) in enumerate(EDGES):
        difference = x[i] - x[j]
        coupling = weights[edge_index] * difference
        dx[i] -= coupling
        dx[j] += coupling

        ds[edge_index] = (
            params.eta_0
            - params.eta_1 * difference**2
            + params.eta_2 * c
            - s[edge_index]
        ) / params.tau_s

        dq[edge_index] = (
            -params.gamma * q[edge_index]
            + params.kappa * difference**2
            - params.rho * c
        ) / params.tau_q

    derivative = State(x=dx, s=ds, q=dq)
    if not np.all(np.isfinite(derivative.pack())):
        raise FloatingPointError("non-finite derivative encountered")
    return derivative


def euler_step(state: State, params: Parameters, dt: float) -> State:
    """Advance one explicit Euler step for transparent reference testing."""

    if not np.isfinite(dt) or dt <= 0.0:
        raise ValueError("dt must be finite and positive")
    rhs = derivatives(state, params)
    return State.unpack(state.pack() + dt * rhs.pack())
